INSERT INTO USERS (FIRST_NAME, LAST_NAME, AGE)
VALUES ('JOHN1','DOE1',1);
INSERT INTO USERS (FIRST_NAME, LAST_NAME, AGE)
VALUES ('JOHN2','DOE2',2);
INSERT INTO USERS (FIRST_NAME, LAST_NAME, AGE)
VALUES ('JOHN3','DOE3',3);
INSERT INTO USERS (FIRST_NAME, LAST_NAME, AGE)
VALUES ('JOHN4','DOE4',4);
INSERT INTO USERS (FIRST_NAME, LAST_NAME, AGE)
VALUES ('JOHN5','DOE5',5);