INSERT INTO USERS (FIRST_NAME, LAST_NAME, AGE)
VALUES ('Eniki','Beniki',1);
INSERT INTO USERS (FIRST_NAME, LAST_NAME, AGE)
VALUES ('Shpili','Villi',2);
INSERT INTO USERS (FIRST_NAME, LAST_NAME, AGE)
VALUES ('Trali','Vali',3);
INSERT INTO USERS (FIRST_NAME, LAST_NAME, AGE)
VALUES ('Tili','Mili',4);
INSERT INTO USERS (FIRST_NAME, LAST_NAME, AGE)
VALUES ('Tuza','Puza',5);

INSERT INTO PRODUCTS (NAME, CATEGORY, COLOR, PARAMETER, COUNT, PRICE)
VALUES ('sock', 'clothes', 'black', 'XXL', 1, 10);
INSERT INTO PRODUCTS (NAME, CATEGORY, COLOR, PARAMETER, COUNT, PRICE)
VALUES ('iPhone', 'phone', 'gold', 'XS', 10, 100);